export const data = {
	title: 'Hello, World!',
	order: 2,
	author: 1,
	status: 'draft',
	password: '',
	reviewer: 'john',
	date: '2021-01-01T12:00:00',
	filesize: 1024,
	dimensions: '1920x1080',
	tags: [ 'photography', 'travel' ],
	address1: '123 Main St',
	address2: 'Apt 4B',
	city: 'New York',
	comment_status: 'open',
	ping_status: true,
	origin: 'New York (JFK)',
	destination: 'Los Angeles (LAX)',
	flight_status: 'on-time',
	gate: 'A12',
	seat: '14F',
};
