export const data = {
	name: 'Danyka Romaguera',
	email: 'aromaguera@example.org',
	phone: '1-828-352-1250',
	plan: 'Business',
	renewal: 'monthly',
	shippingAddress: 'N/A',
	shippingCity: 'N/A',
	shippingPostalCode: 'N/A',
	shippingCountry: 'N/A',
	billingAddress: 'Danyka Romaguera, West Myrtiehaven',
	billingCity: 'West Myrtiehaven',
	billingPostalCode: '80240-4282',
	vat: 10,
	commission: 5,
	hasDiscount: true,
	cost: 100,
	quantity: 5,
	total: 500,
};
